apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      run: backend
  template:
    metadata:
      labels:
        run: backend
    spec:
      containers:
        - image: ghcr.io/anirv20/simple-fortune-cookie-backend:latest
          name: backend
          env:
            - name: REDIS_DNS
              value: redis
            - name: REDIS_PASSWORD
              value: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81