name: CI tests
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  clone:
    name: Clone Git repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Upload Repo
      uses: actions/upload-artifact@v3
      with:
        name: code
        path: .
  test-frontend:
    name: Test frontend
    runs-on: ubuntu-latest
    needs: clone
    steps:
    - name: Download code
      uses: actions/download-artifact@v3
      with:
        name: code
        path: .
    - name: Setup Go environment
      uses: actions/setup-go@v4.1.0
      with:
        go-version: '1.21.0'
    - name: Build frontend
      run: cd frontend && go build
    - name: Run frontend tests
      run: cd frontend && go test
  test-backend:
    name: Test backend
    runs-on: ubuntu-latest
    needs: clone
    steps:
    - name: Download code
      uses: actions/download-artifact@v3
      with:
        name: code
        path: .
    - name: Setup Go environment
      uses: actions/setup-go@v4.1.0
      with:
        go-version: '1.21.0'
    - name: Build backend
      run: cd backend && go build
    - name: Run backend tests
      run: cd backend && go test
